name: rosseti
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  mobx_provider: ^0.0.4
  json_annotation: ^3.1.1
  copy_with_extension: ^1.4.0
  flutter_spinkit: ^4.1.2+1
  get_it: ^5.0.1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.8
  bubble: ^1.1.9+1
  graphql: ^3.1.0
  dropdown_formfield: ^0.1.3
  fluttericon: ^1.0.7
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.0
  copy_with_extension_gen: ^1.4.0
  chopper_generator: ^3.0.6
  gql_code_gen: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
